# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

### Beck McGowan

title: Beck McGowan
author: Beck
email: hello@beckmcgowan.com
description: "{ software developer, hobby-collector, cat parent; }"
baseurl: ""
url: "https://bmgamedev.github.io"

#~~~~~~~~~~~~~~~~~~~~~~

twitter: mcgowanbeck
github:  bmgamedev
linkedin: "#"

#~~~~~~~~~~~~~~~~~~~~~~

#paginate: 4
#permalink: /blog/:year/:title/
#paginate_path: /blog/page:num/

#~~~~~~~~~~~~~~~~~~~~~~

collections:
  projects:
    ouput: true
    permalink: /projects/:name/
    order:
      #- topic-modelling.md
      - nightmarevania.md
      - honours.md
      - game-jams.md
      - academic.md

#~~~~~~~~~~~~~~~~~~~~~~

# Theme settings

theme: minima
  
#~~~~~~~~~~~~~~~~~~~~~~

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank

compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages
  - _projects

exclude:
  - README.md
  - LICENSE.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
